let currentReportsData = null;

async function loadReports() {
  const immunizationReport = document.getElementById('immunizationReport');
  const coverageReport = document.getElementById('coverageReport');
  const overdueReport = document.getElementById('overdueReport');
  const stockReport = document.getElementById('stockReport');
  const usageReport = document.getElementById('usageReport');
  const appointmentReport = document.getElementById('appointmentReport');

  if (!immunizationReport) return;

  try {
    const response = await fetch(`${API_BASE_URL}/reports`, { headers: getAuthHeaders() });
    const result = await response.json();
    if (!response.ok) throw new Error(result.message || 'Failed to load reports');

    const data = result.data;
    currentReportsData = data;

    immunizationReport.innerHTML = `<div class="alert alert-info"><strong>${data.totalVaccinations}</strong> vaccinations recorded.</div>`;
    coverageReport.innerHTML = `<div class="alert alert-success"><strong>${data.totalChildren}</strong> children registered.</div>`;
    overdueReport.innerHTML = `<div class="alert alert-warning"><strong>Overdue tracking</strong> is available from vaccination records and appointments.</div>`;
    stockReport.innerHTML = `<div class="alert alert-secondary"><strong>${data.lowStock}</strong> batches at low stock levels.</div>`;
    usageReport.innerHTML = `<div class="alert alert-primary"><strong>${data.upcomingAppointments}</strong> upcoming appointments scheduled.</div>`;
    appointmentReport.innerHTML = `<div class="alert alert-dark"><strong>${data.totalChildren}</strong> children in the system.</div>`;
  } catch (error) {
    [immunizationReport, coverageReport, overdueReport, stockReport, usageReport, appointmentReport].forEach((el) => {
      el.innerHTML = `<div class="alert alert-danger">${error.message}</div>`;
    });
  }
}

function applyDateFilter() {
  loadReports();
}

function downloadCurrentReportPdf() {
  if (!currentReportsData) {
    alert('Please generate a report first');
    return;
  }

  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 15;
  const lineHeight = 7;
  const margin = 10;

  const user = getCurrentUser();
  const timestamp = new Date().toLocaleString();

  doc.setFontSize(16);
  doc.text('Child Vaccination System - Reports', margin, yPosition);
  yPosition += 10;

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated by: ${user?.name || 'System'}`, margin, yPosition);
  yPosition += lineHeight;
  doc.text(`Generated on: ${timestamp}`, margin, yPosition);
  yPosition += lineHeight;

  doc.setTextColor(0);
  yPosition += 5;

  const addSection = (title, data) => {
    if (yPosition > pageHeight - 20) {
      doc.addPage();
      yPosition = 15;
    }
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text(title, margin, yPosition);
    yPosition += lineHeight;
    doc.setFont(undefined, 'normal');
    doc.setFontSize(10);
  };

  addSection('Summary Report', null);
  const summaryData = [
    `Total Children Registered: ${currentReportsData.totalChildren}`,
    `Total Vaccinations Recorded: ${currentReportsData.totalVaccinations}`,
    `Upcoming Appointments: ${currentReportsData.upcomingAppointments}`,
    `Low Stock Batches: ${currentReportsData.lowStock}`,
  ];
  summaryData.forEach((line) => {
    doc.text(`• ${line}`, margin + 5, yPosition);
    yPosition += lineHeight;
  });

  addSection('Immunization Report', null);
  doc.text(`• Total vaccinations administered: ${currentReportsData.totalVaccinations}`, margin + 5, yPosition);
  yPosition += lineHeight;

  addSection('Coverage Analysis', null);
  doc.text(`• Registered children: ${currentReportsData.totalChildren}`, margin + 5, yPosition);
  yPosition += lineHeight;

  addSection('Inventory Status', null);
  doc.text(`• Batches at low stock: ${currentReportsData.lowStock}`, margin + 5, yPosition);
  yPosition += lineHeight;

  addSection('Appointment Schedule', null);
  doc.text(`• Upcoming appointments: ${currentReportsData.upcomingAppointments}`, margin + 5, yPosition);
  yPosition += lineHeight;

  const fileName = `vaccination-report-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}

window.applyDateFilter = applyDateFilter;
window.downloadCurrentReportPdf = downloadCurrentReportPdf;
document.addEventListener('DOMContentLoaded', loadReports);
